# Trigger rebuild v2
[phases.setup]
...
[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_pgsql", "php82Extensions.pgsql", "php82Extensions.bcmath", "php82Extensions.gd", "php82Extensions.zip", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.curl", "php82Extensions.tokenizer", "composer", "nodejs_20"]

[phases.build]
cmds = [
    "mkdir -p /app/storage/logs",
    "touch /app/storage/logs/laravel.log",
    "chmod -R 777 /app/storage",
    "composer install --optimize-autoloader --no-dev --ignore-platform-reqs", 
    "npm install", 
    "npm run build",
    "php artisan config:cache",
    "php artisan event:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan migrate:fresh --seed --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"
